### PR TITLE
WIP: Display the browser installation message on the first launch

### PR DESCRIPTION
**Pull request by Monsterovich**
Perhaps there is a way to make the install function asynchronous.

### CODE REVIEW

**Comment by Monsterovich** [comment]
Or maybe the best thing to do is just move the browser installation to the post install script in setup.py?

**Comment by eggplants** [comment]
Oh, sounds nice feature.
Maybe I should install at post-install step.

https://stackoverflow.com/a/36902139

**Comment by Monsterovich** [comment]
> Oh, sounds nice feature. Maybe I should install at post-install step.
> 
> https://stackoverflow.com/a/36902139

I found a way to run the browser installation in an asynchronous function without locking the thread, even canceling the task works. That's why I closed this PR.

https://github.com/eggplants/deepl-cli/pull/76

As some of the suggested solutions say, post install will only work when installing from an archive. This means that pip installation will not work (if I understood them correctly).

**Comment by Monsterovich** [comment]
Here's another catch, the cache can be cleared after installation, so installing within the app is necessary.

**Comment by eggplants** [comment]
>Note: The solution below only works when installing a source distribution zip or tarball, or installing in editable mode from a source tree. It will not work when installing from a binary wheel

:skull::bone:

**Pull request closed without merging**
