### PR TITLE
Feat dom submit

### PR DESCRIPTION
**Pull request by Monsterovich**

### CODE REVIEW

**Comment by eggplants** [comment]
Could you add the test for `use_dom_submit=True`?

**Comment by Monsterovich** [comment]
> Could you add the test for `use_dom_submit=True`?

Done.

**Comment by eggplants** [comment]
Hmm... You're right, the translation results have changed somehow.

image

**Comment by eggplants** [comment]
`こんにちは` should be replaced with `こんにちは。`.

image

>Perhaps we should use a less complicated languages like German or Russian?

I think the same problem could occur even in German or Russian. Anyway, for now I would like to test from Japanese to English.

**Comment by eggplants** [comment]
:thinking: 

image

image

**Pull request merged**
